# Generated by Django 6.0.4 on 2026-05-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_employer_until',
            field=models.DateTimeField(blank=True, help_text='Stripe işəgötürən abunəliyinin aktiv olduğu müddətin sonu.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_seeker_until',
            field=models.DateTimeField(blank=True, help_text='Stripe namizəd abunəliyinin aktiv olduğu müddətin sonu.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
