# Generated by Django 6.0.4 on 2026-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_premium_employer_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='tagline',
            field=models.CharField(blank=True, help_text='İctimai səhifədə başlıq altında bir sətir.', max_length=160),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_employer_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='premium_seeker_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
