# Generated by Django 6.0.4 on 2026-05-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_display_name', models.CharField(blank=True, help_text='Boşdursa, göstərici üçün employer e-poçtu istifadə oluna bilər.', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_mode', models.CharField(choices=[('remote', 'Uzaqdan'), ('hybrid', 'Hibrid'), ('onsite', 'Ofisdə')], default='remote', max_length=20)),
                ('salary_display', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
