# Generated by Django 6.0.4 on 2026-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_jobseekerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
